### ISSUE TITLE
Not working in controller ports B, C or D

### ISSUE THREAD

**Issue by soniccd123** [charcole/Dreamcast-PopnMusic#4]
Hey, awesome project!!! Thank you very much for this

This will sound strange, but I was thinking of using this project as a internal VMU for my Dreamcast, like left a Raspberry Pi Pico always connected to controller port D and use it as internal storage. The problem is that the Pop 'n Music is only being found in my Dreamcast when connected to port A. I've checked other ports and they work normally with real controllers. I know this is not the scope of this project, but would be possible to make the Pop 'n Music work in other controller ports?

Thanks again

soniccd123

**Comment by charcole** [comment]
Hey,

I think I've already fixed that issue with this commit https://github.com/charcole/Dreamcast-PopnMusic/commit/89284070acaf778d3e2a620d54070b56d0ca5378. Are you using "First Release" and not latest perhaps? Or is there still an issue there?

Good luck with you project. Internal storage sounds a neat idea.

Charlie

**Comment by soniccd123** [comment]
Thanks! Gonna try to compile the latest commit, stupid me didn't think of that lol. It worked!

I'm thinking of maybe also trying to modify your Maple protocol implementation to make the Pi Pico communicate as a VMU throught the controller VMU connector. Would be very nice if it works, one could embed storage inside the controller or even make new VMU memory cards!

Thanks again!
