### ISSUE TITLE
Relicensing my fork

### ISSUE THREAD

**Issue by mackieks** [charcole/Dreamcast-PopnMusic#6]
Hi Charlie! First off, let me say thanks for writing this well-organized Maple Bus transceiver code! I [forked your codebase](https://github.com/mackieks/MaplePad) last year and have made tons of progress toward a general-purpose Dreamcast controller emulator. I did detach my fork from your repo earlier this year as its scope has grown beyond your original project quite a bit. Initially I was mostly focused on Dreamcast portablizing, but many people have reached out to me about using MaplePad for custom arcade sticks or custom DC controllers.

I'm wondering if you're open to me relicensing my fork under [CC Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/). It's a slightly more permissive ["Free Culture"](https://creativecommons.org/share-your-work/public-domain/freeworks) license that requires derivative works to be open-sourced, without limiting folks' ability to monetize an arcade stick or custom controller if they so choose. I think moving from NC to SA helps position the project as a true FOSS work and will encourage thoughtful reuse without giving away the farm, so to speak. 

Let me know what you think!

**Comment by charcole** [comment]
Thanks for asking. Yes, I don’t have any objections to you relicensing as CC BY-SA.  As long as you continue to give me some credit then I’m OK with it.

You’ve made a very cool board there, might have to try building one myself!

**Comment by mackieks** [comment]
Fantastic, I really appreciate it! I'll make sure you remain credited no matter where the project goes in the future. 

Yup, it's a fun little board to assemble and the OLED VMU is pretty nifty! Definitely give it a shot. 👍
